### ISSUE TITLE
可以直接编辑README.md，不用上传图片，放到相应的时间下面就好了。

### ISSUE THREAD

**Issue by iamverycute** [iamverycute/wugao#4]
![无标题ddd](https://github.com/iamverycute/wugao/assets/31397186/a41c84bf-5534-49dc-b908-94acfa81bf4d)

**Comment by caikun233** [comment]
其他用户没有权限编辑代码和readme

**Comment by iamverylovely** [comment]
@caikun233 点击文件列表中的“readme.md”，就会出现编辑按钮。

**Comment by m-d-z-z** [comment]
> 其他用户没有权限编辑代码和readme

提PR不就行了（
